# parameterstore 설정 값
spring:
  config:
    import: "aws-parameterstore:/startup-team-service/prod/"

  cloud:
    aws:
      s3:
        bucket: {S3버킷이름}

management:
  endpoint:
    health:
      show-details: never
  info:
    env:
      enabled: true

info:
  app:
    message: "${APP_MESSAGE}"
    team-name: "${team-name}"

logging:
  level:
    root: INFO