spring:
  datasource:
    url: ${DB_URL} # 환경변수나 Parameter Store
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update # 운영에선 데이터를 날리면 안 되니 update로 설정
    show-sql: false # 운영에선 로그가 너무 많아지면 안 되니 끔

# 운영 환경 로깅
logging:
  level:
    root: INFO