# 로컬 H2 DB 설정
spring:
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL;DB_CLOSE_DELAY=-1 # 메모리 모드로 실행
    driver-class-name: org.h2.Driver
    username: {유저네임}
    password: {비밀번호}

  jpa:
    hibernate:
      ddl-auto: create # 서버 켤 때마다 테이블 새로 생성
    show-sql: true # 실행되는 쿼리를 로그로 출력
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect

  cloud:
    aws:
      credentials:
        access-key: {"AKIA... 입력"}
        secret-key: {"iXb... 입력"}

logging:
  level:
    kr.spartaclub.startupteamservice: DEBUG # 로컬에선 상세히 보기 위해 DEBUG