spring:
  application:
    name: startup-team-service
  profiles:
    active: local # 기본 실행값은 로컬로 설정

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  # 공통 AWS 기본 설정
  cloud:
    aws:
      region:
        static: ap-northeast-2
      stack:
        auto: false
      s3:
        bucket: "startup-team-service-jhsparta3118-files"

# JPA 및 서버 기본 설정
spring.jpa:
  hibernate:
    ddl-auto: update
  show-sql: true

server:
  port: 8080